<img src="https://upload.wikimedia.org/wikipedia/commons/3/31/NumPy_logo_2020.svg" alt="numpy" width="600"/>

**Numpy** es una biblioteca para Python que da soporte para crear vectores y matrices grandes multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel para operar con ellas. 

# Elementos básicos

Importación del paquete NumPy

In [ ]:
import numpy as np

### Crear un array

In [ ]:
matriz = [[0, 1, 2],[3, 4, 5],[6, 7, 8]]
array1 = np.array(matriz)
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
type(array1)

numpy.ndarray

### Rangos

`arange(inicio, fin, incremento)`, *fin* no se incluye en el array

In [ ]:
np.arange(5, 30, 5)

array([ 5, 10, 15, 20, 25])

In [ ]:
np.arange(1, 1.55, 0.1) # también con floats

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5])

#### Atributos de array

In [ ]:
print("Número de dimensiones (ejes o índices):", array1.ndim)
print("Número de elementos:", array1.size)
print("Tamaño en bytes de cada elemento:", array1.itemsize)
print("Tipo de los elementos:", array1.dtype)
print("Dimensiones:", array1.shape)

Número de dimensiones (ejes o índices): 2
Número de elementos: 9
Tamaño en bytes de cada elemento: 8
Tipo de los elementos: int64
Dimensiones: (3, 3)


## Eliminación de filas o columnas

In [ ]:
array1 = np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8]])
# delete: 3er argumento->0:filas, 1:columnas, 2º argumento->número de fila/columna a eliminar
print("Array inicial")
print(array1,"\n")

print("Eliminando la tercera columna:")
array2 = np.delete(array1,2,1) 
print(array2,"\n")

print("Array inicial")
print(array1,"\n")

print("Eliminando la segunda fila:")
array3 = np.delete(array1,1,0) 
print(array3,"\n")

Array inicial
[[0 1 2]
 [3 4 5]
 [6 7 8]] 

Eliminando la tercera columna:
[[0 1]
 [3 4]
 [6 7]] 

Array inicial
[[0 1 2]
 [3 4 5]
 [6 7 8]] 

Eliminando la segunda fila:
[[0 1 2]
 [6 7 8]] 



## Tipos de datos

Con `np.array()` se pueden crear arrays con valores:
 * reales (floats)
 * enteros (int)
 * complejos
 * lógicos (booleans)
 * texto (strings)
 
El  atributo `dtype` permite conocer el tipo de los datos.

In [ ]:
np.array([[1.0, 2.0], [3.0, 4.0]]).dtype

dtype('float64')

In [ ]:
np.array([[1+2j, 3+4j], [3-4j, 1-2j]]).dtype

dtype('complex128')

In [ ]:
np.array([True, False]).dtype

dtype('bool')

In [ ]:
np.array(['Numpy', 'Pandas', 'Matplotlib']).dtype

dtype('<U10')

### Redistribución de los elementos

In [ ]:

array1 = np.array([[0,1,2,3,4,5,6,7],[8,9,10,11,12,13,14,15]])
print(array1.shape)
array2 = array1.reshape(4, 4) # el número de elementos tiene que ser idéntico
array2

(2, 8)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## Vistas 
El método `reshape` devuelve una vista, en lugar de un nuevo array.<br>
Si se modifica una vista, el array del que proviene, también se ve modificado.

In [ ]:
array1[0][0] = 42
print(array1,"\n")
print(array2) 

[[42  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]] 

[[42  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
a = np.arange(9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Diferencia entre copia y vista

vista: objeto diferente trabajando sobre los mismos datos

In [ ]:
a = np.arange(4)
b = a
b[0]=10
print(a)
print(b)

[10  1  2  3]
[10  1  2  3]


copia independiente

In [ ]:
a = np.arange(4)
b = np.copy(a)
b[0]=10
print(a)
print(b)

[0 1 2 3]
[10  1  2  3]


## Más formas de crear arrays

#### Especificación del tipo en la construcción

In [ ]:
np.arange(1, 160, 10, dtype=np.int8)

array([   1,   11,   21,   31,   41,   51,   61,   71,   81,   91,  101,
        111,  121, -125, -115, -105], dtype=int8)

`linspace(`*inicio*, *fin*, *num*`)` calcula el incremento para generar *num* valores equiespaciados, incluyendo el valor *stop* 

In [ ]:
np.linspace(1, 2, 11)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

### Datos homogéneos

In [ ]:
np.zeros([4, 4]) # por defecto, reales. Paréntesis o corchetes internos

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Especificando el tipo de dato:

In [ ]:
np.zeros((4, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.ones((2, 3, 3)) # corchetes o paréntesis internos para las dimensiones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

Si se quiere una matriz con el mismo valor en todas las posiciones: 

In [ ]:
np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])

In [ ]:
7*np.ones((2, 2))

array([[7., 7.],
       [7., 7.]])

### Matrices diagonales

In [ ]:
print(np.eye(2)) # unidad cuadrada (dimensiones en el argumento)

[[1. 0.]
 [0. 1.]]


In [ ]:
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

El argumento `k` permite indicar la columna del primer elemento:

In [ ]:
np.diag([1, 2, 3, 4], k=1) # también puede ser negativo

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

Si recibe como argumento una matriz 2D, devuelve la diagonal: 

In [ ]:
np.diag(np.arange(16).reshape(4, 4))

array([ 0,  5, 10, 15])

In [ ]:
2*np.eye(3)+np.eye(3, k=1)+np.eye(3, k=-1)

array([[2., 1., 0.],
       [1., 2., 1.],
       [0., 1., 2.]])

# Números aleatorios

In [ ]:
np.random.rand(5, 2) # intervalo [0,1)

array([[0.35781727, 0.50099513],
       [0.68346294, 0.71270203],
       [0.37025075, 0.56119619],
       [0.50308317, 0.01376845],
       [0.77282662, 0.88264119]])

La semilla hace que se genere la misma secuencia aleatoria. <br>
De esta forma los experimentos son repetibles.

In [ ]:
np.random.seed(1234)
print(np.random.rand(5, 2),"\n")
np.random.seed(1234)
print(np.random.rand(5, 2))


[[0.19151945 0.62210877]
 [0.43772774 0.78535858]
 [0.77997581 0.27259261]
 [0.27646426 0.80187218]
 [0.95813935 0.87593263]] 

[[0.19151945 0.62210877]
 [0.43772774 0.78535858]
 [0.77997581 0.27259261]
 [0.27646426 0.80187218]
 [0.95813935 0.87593263]]


# Indexado y segmentación

### Arrays 1D

In [ ]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


Acceso a un único elemento:

In [ ]:
a[2]=0
print(a)

[0 1 0 3 4 5 6 7 8 9]


Segmento desde la posición 7 hasta el final:

In [ ]:
a2 = a[7:]
print(a2)

[7 8 9]


Los segmentos de arrays son vistas:

In [ ]:
aa1 = np.array([[1,3],[7,9]] )
aa2 = aa1[0,:]
aa3 = aa1[:,0]
aa1[0,0]=0
print(aa1,"\n")
print(aa2,"\n")
print(aa3)

[[0 3]
 [7 9]] 

[0 3] 

[0 7]


Segmento desde la posición 3 hasta el final con incremento de 2

In [ ]:
a[3::2]

array([3, 5, 7, 9])

Indice negativos: indexan desde el final (-1, -2 ...)<br>
Inversión del array:

In [ ]:
print(a[::-1])      # todos los datos desde el final con incremento = -1
print(a[::2])       # todos los datos desde el principio con incremento = 2

[9 8 7 6 5 4 3 0 1 0]
[0 0 4 6 8]


### Multidimensionalidad

In [ ]:
a = np.arange(9).reshape(3, 3)
print(a)
print(a[1,2])
a[1][2]=0
print(a[1][2]) # el indexado a[x][y] es equivalente a[x,y]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
5
0


In [ ]:
b = np.arange(40).reshape(5, 8)
print(b,"\n")
b[-3:, -2:]

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]] 



array([[22, 23],
       [30, 31],
       [38, 39]])

In [ ]:
b[:, 3]

array([ 3, 11, 19, 27, 35])

In [ ]:
b[1, 3:6]

array([11, 12, 13])

In [ ]:
b[1::2, ::3]

array([[ 8, 11, 14],
       [24, 27, 30]])

## Indexado buleano

In [ ]:
c = np.arange(40).reshape(5, 8)
print(c)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]]


In [ ]:
c % 3 == 0

array([[ True, False, False,  True, False, False,  True, False],
       [False,  True, False, False,  True, False, False,  True],
       [False, False,  True, False, False,  True, False, False],
       [ True, False, False,  True, False, False,  True, False],
       [False,  True, False, False,  True, False, False,  True]])

In [ ]:
c[c%3 == 0] # aplana el array antes de aplicar el indexado

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39])

La primera tupla (o lista) indica las filas y la segunda, las columnas: devuelve copia

In [ ]:
ccc=c[(0, 1, 2, 2, 3, 3), (0, 4, 2, 5, 3, 4)]
c[0,0]=-1
print(c,"\n")
print(ccc)

[[-1  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]] 

[ 0 12 18 21 27 28]


Método `where`:

In [ ]:
d = np.arange(9).reshape(3, 3)
print(d,"\n")
print("Arrays de filas y columnas:",np.where(d > 4))    # posiciones de los que cumplen
print("Valores que cumplen",d[np.where(d > 5)]) # valores de los que cumplen (aplana antes de devolver)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

Arrays de filas y columnas: (array([1, 2, 2, 2]), array([2, 0, 1, 2]))
Valores que cumplen [6 7 8]


# Ejes

Crear un array y calcular la suma sobre todos sus elementos.

In [ ]:
a = np.arange(9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Suma a lo largo del eje 0 (eje x): por columnas

In [ ]:
np.sum(a, axis=0)

array([ 9, 12, 15])

Suma a lo largo del eje 1 (eje y): suma por filas

In [ ]:
np.sum(a, axis=1)

array([ 3, 12, 21])

Máximos y mínimos:

In [ ]:
print(a,"\n")
print(np.max(a, axis=1),"\n")    # máximo para cada fila
print(np.argmax(a, axis=1)) # índice (posición) del máximo para cada fila

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[2 5 8] 

[2 2 2]


### Ejes en más de dos dimensiones

Array 3D:

In [ ]:
d = np.arange(24).reshape(2, 3, 4)
print(d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


Generar un array 2D: 

In [ ]:
d[1, :, :]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Por ejemplo con el eje 1:

In [ ]:
d[:, 0, :]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [ ]:
print(d[0],"\n") # es equivalente a:
print(d[0,:,:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Los (tres) puntos suspensivos representan al resto de las dimensiones:

In [ ]:
print(d[..., 0],"\n")
print(d[:,:,0]) # equivalente a la anterior

[[ 0  4  8]
 [12 16 20]] 

[[ 0  4  8]
 [12 16 20]]


In [ ]:
print(d[0,...],"\n")
print(d[0,:,:]) # equivalente a la anterior

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(d[0,1,...],"\n")
print(d[0,1,:])  # equivalente a la anterior

[4 5 6 7] 

[4 5 6 7]


# Apilado de vectores

In [ ]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1,v2,v1,v2]),"\n") # vertical
print(np.hstack([v1,v2,v1,v2]))      # horizontal

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]] 

[1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]


# Operaciones matemáticas

In [ ]:
a = np.arange(4)
b = np.arange(4, 8) # el segundo valor no se alcanza
print(a)
print(b)

[0 1 2 3]
[4 5 6 7]


In [ ]:
a+b

array([ 4,  6,  8, 10])

In [ ]:
a*b   # producto elemento por elemento

array([ 0,  5, 12, 21])

Las operaciones se aplican elemento por elemento:

In [ ]:
a = np.arange(4).reshape(2, 2)
b = np.arange(4, 8).reshape(2, 2)
print(a,"\n")
print(b)

[[0 1]
 [2 3]] 

[[4 5]
 [6 7]]


In [ ]:
a*b

array([[ 0,  5],
       [12, 21]])

In [ ]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)
print(x,"\n")
print(y)

[[1. 2.]
 [3. 4.]] 

[[5. 6.]
 [7. 8.]]


In [ ]:
print(np.add(x, y),"\n")      # idéntico a x+y
print(np.subtract(x, y),"\n") # idéntico a x-y
print(np.multiply(x, y),"\n") # idéntico a x*y
print(np.sqrt(x))             # raíz cuadrada por elmentos

[[ 6.  8.]
 [10. 12.]] 

[[-4. -4.]
 [-4. -4.]] 

[[ 5. 12.]
 [21. 32.]] 

[[1.         1.41421356]
 [1.73205081 2.        ]]


Producto matricial, con tres notaciones distintas:

In [ ]:
np.dot(a, b)

array([[ 6,  7],
       [26, 31]])

In [ ]:
a.dot(b)

array([[ 6,  7],
       [26, 31]])

In [ ]:
a @ b

array([[ 6,  7],
       [26, 31]])

# Velocidad

#### La orden mágica de Jupyter `%%timeit` calcula el tiempo que tarda en ejecutarse la línea que la sigue (solo una). <br>Tiene que estar en la primera línea de la celda.<br>La instrucción en su misma línea se considera inicialización y no se tiene en cuenta para calcular el tiempo.

In [ ]:
%%timeit a = np.arange(1000000)
a**2

The slowest run took 6.30 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 5: 804 µs per loop


In [ ]:
%%timeit a = range(1000000)
[valor**2 for valor in a] # genera lista con los cuadrados de x

1 loop, best of 5: 310 ms per loop


In [ ]:
%%timeit a = np.arange(100000)
np.sin(a)

100 loops, best of 5: 4.1 ms per loop


In [ ]:
import math # no puede ir en la misma celda que %%timeit.

In [ ]:
%%timeit a = range(100000)
[math.sin(valor) for valor in a]

10 loops, best of 5: 19.7 ms per loop


## Broadcasting
#### Los operadores se extienden hasta tener las dimensiones necesarias para la operación.

In [ ]:
a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a+1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a+np.arange(4) # Se replica la primera fila [0, 1, 2, 3] en las dos siguientes

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [ ]:
# a+np.arange(3) # esto da un error porque no puede expandirlo para que sea compatible

Ejemplo que construye las tablas de multiplicar, multiplicando un vector fila por uno columna:

In [ ]:
np.arange(1, 11)*np.arange(1, 11).reshape(10, 1) # reshape se aplica antes que el producto

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

Una alternativa a `reshape` consiste en añadir nuevos ejes con `newaxis`:

In [ ]:
a = np.arange(5)
b = a[:, np.newaxis]
print(a,"\n\n",b)

[0 1 2 3 4] 

 [[0]
 [1]
 [2]
 [3]
 [4]]


In [ ]:
a.shape, b.shape

((5,), (5, 1))

# Álgebra lineal

In [ ]:
from numpy import linalg

In [ ]:
a = np.arange(9).reshape(3, 3)
print("Determinante:",np.linalg.det(a))

Determinante: 0.0


In [ ]:
b = np.arange(4).reshape(2, 2)
autovalores, autovectores = linalg.eig(b)
print('Autovalores:',autovalores)
print("\n",'Autovectores:\n',autovectores)

Autovalores: [-0.56155281  3.56155281]

 Autovectores:
 [[-0.87192821 -0.27032301]
 [ 0.48963374 -0.96276969]]


## Funciones en el paquete sklearn 

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

y_real = np.array([3,  -0.5, 2, 7])
y_est  = np.array([2.5, 0.0, 2, 8])

print("Error medio cuatrático:", mean_squared_error(y_real, y_est))
print("Error medio absoluto:", mean_absolute_error(y_real, y_est))

Error medio cuatrático: 0.375
Error medio absoluto: 0.5
